//`include "./../src/rtl/test.v"
//`include "./../src/rtl/fifo.v"
//`include "./../src/rtl/fifo_tb.v"
//`include "./../src/rtl/lfsr.v"
//`include "./../src/ICCAD2015benchmarks/superblue7/superblue7.v"
//`include "./../src/rtl/xor_mul2.v"
//`include "./../src/rtl/watchdog/wd_define.v"
//`include "./../src/rtl/watchdog/wd_top.v"
//`include "./../src/rtl/watchdog/wd_apb.v"
//`include "./../src/rtl/watchdog/watchdog.v"
//`include "./../src/superblue7.v"
//`include "./add.v"
//`include"sequencial.v"
//`include "sequencial_fsm.sv"
`include "../lat.v"
